// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhxszjbfwtiezgtgfxcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoeHN6amJmd3RpZXpndGdmeGNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjU3Mzg2MTksImV4cCI6MjA0MTMxNDYxOX0.xo_TyO6u5lHTKVJHh4J6aKV5k1-5wF0BfGjEgGpNqLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});